applied PackageJanitor

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -14,6 +14,7 @@ jobs:
     strategy:
       matrix:
         image: [gapsystem/gap-docker, gapsystem/gap-docker-master]
+      fail-fast: false
     runs-on: ubuntu-latest
     container:
       image: ${{ matrix.image }}
@@ -47,3 +48,14 @@ jobs:
           TERM=dumb make -C ZariskiFrames -j $(nproc) --output-sync ci-test
           cp ./Toposes/.codecov.yml ./
           curl -s https://codecov.io/bash | bash
+          git config --global user.name "Bot"
+          git config --global user.email "empty"
+          cd Toposes
+          CUR_SHA=$(git rev-parse --verify HEAD)
+          if [ "${{ matrix.image }}" = "gapsystem/gap-docker" ] && [ "$CUR_SHA" = "$(git rev-parse origin/master)" ] && [ $(dirname "$GITHUB_REPOSITORY") = "homalg-project" ]; then \
+            git worktree add gh-pages/ gh-pages || (echo "There was an error. Make sure there is a branch named 'gh-pages'. See https://github.com/homalg-project/PackageJanitor#error-there-was-an-error-make-sure-there-is-a-branch-named-gh-pages"; exit 1); \
+            git checkout master; \
+            LANG=C.UTF-8 ./make_dist.sh --token "${{ secrets.GITHUB_TOKEN }}"; \
+          else \
+            echo "Not making a release."; \
+          fi
